version: '3.3'

# datavaultbuilder version is defined as DVB_TAG in the file '.env'

services:

  exasol:
    build: .
    volumes:
            - mydata:/exa
    ports:
      - '8888:8563'
      - '9043:443'
      - '9583:6583'
    privileged: true

volumes:
  mydata:
