apiVersion: v1
kind: Service
metadata:
  name: exasol
  namespace: dev
spec:
  selector:
    app: exasol
  type: LoadBalancer
  ports:
    - port: 8888
      targetPort: 8563
---
apiVersion: v1
kind: Service
metadata:
  name: exasol-fs
  namespace: dev
spec:
  selector:
    app: exasol
  type: LoadBalancer
  ports:
    - port: 8889
      targetPort: 2580
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: exasol
  namespace: dev
spec:
  selector:
    matchLabels:
      app: exasol
  serviceName: exasol-service
  replicas: 1
  template:
    metadata:
      labels:
        app: exasol
    spec:
      containers:
        - ports:
          - containerPort: 8563
          - containerPort: 443
          - containerPort: 2580
          securityContext:
            privileged: true  
          image: "alligatorcompany/acs-exasol:1.0.2"
          name: exasol
          readinessProbe:
            exec: 
              command:
              - /work/readiness.sh
            initialDelaySeconds: 60
            periodSeconds: 5
            failureThreshold: 5
          livenessProbe:
            tcpSocket:
              port: 8563
            initialDelaySeconds: 90
            periodSeconds: 60
          volumeMounts:
            - name: exasol-disk
              mountPath: /exa

            
  volumeClaimTemplates:
    - metadata:
        name: exasol-disk
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi
