apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

components:
- ../../component/airflow
- ../../component/exasol
- ../../component/dvb
- ../../component/kafka-operator
- ../../component/kafka-broker
- ../../component/kafka-sr
- ../../component/superset
- ../../component/jasper

namespace: dev
commonLabels:
  environment: dev