apiVersion: v1
kind: Service
metadata:
  name: kafka-broker
  namespace: dev
spec:
  selector:
    strimzi.io/name: my-cluster-kafka-bootstrap
  type: LoadBalancer
  ports:
    - port: 9092
      targetPort: 9092
