CREATE OR REPLACE python3 scalar SCRIPT STAGING.VI_COMPONENT (URL VARCHAR(3500) ASCII, USERNAME VARCHAR(3500), PASSWORD VARCHAR(3500))
EMITS (
    NAMESPACE_GUID VARCHAR(3500) ASCII,
    NAMESPACE_NAME VARCHAR(3500) ASCII,
    PACKAGE_GUID VARCHAR(3500) ASCII,
    PACKAGE_NAME VARCHAR(3500) ASCII,
    PACKAGE_AUTOSARCLUSTER VARCHAR(3500) ASCII,
    PACKAGE_CURRENTQUALITYPROCESS VARCHAR(3500) ASCII, 
    PACKAGE_DESCRIPTION VARCHAR(3500) ASCII, 
    PACKAGE_HASSAFETYREQUIREMENTS VARCHAR(3500) ASCII, 
    PACKAGE_LAYER VARCHAR(3500) ASCII, 
    PACKAGE_REPORTCLASSIFICATION VARCHAR(3500) ASCII, 
    PACKAGE_REPORTINGQSTATUS VARCHAR(3500) ASCII, 
    PACKAGE_SHORTNAME VARCHAR(3500) ASCII, 
    PACKAGE_TARGETQUALITYPROCESS VARCHAR(3500) ASCII, 
    PACKAGE_TARGETQUALITYSTATUS VARCHAR(3500) ASCII, 
    PACKAGE_USEDINPRODUCT VARCHAR(3500) ASCII,
    PACKAGE_USERGUIDRESPONSIBLE VARCHAR(3500) ASCII,
    COMPONENT_GUID VARCHAR(3500) ASCII,
    COMPONENT_VERSION VARCHAR(3500) ASCII,
    COMPONENT_IMPLEMENTATIONVERSION VARCHAR(3500) ASCII,
    COMPONENT_CREATIONDATEALM VARCHAR(3500) ASCII,
    COMPONENT_MODTIMEALM VARCHAR(3500) ASCII,
    COMPONENT_REVISIONALM VARCHAR(3500) ASCII,
    COMPONENT_CREATIONDATESVN VARCHAR(3500) ASCII,
    COMPONENT_REVISIONSVN VARCHAR(3500) ASCII,
    COMPONENT_LASTMODDATE VARCHAR(3500) ASCII,
    COMPONENT_SERVERURL VARCHAR(3500) ASCII,
    COMPONENT_DESCRIPTION VARCHAR(3500) ASCII,
    COMPONENT_PATHTESTREPORTS VARCHAR(3500) ASCII,
    COMPONENT_QAAPPROVALNOTE VARCHAR(3500) ASCII,
    COMPONENT_QACHECK VARCHAR(3500) ASCII,
    COMPONENT_QLEVEL VARCHAR(3500) ASCII,
    COMPONENT_RELEASESTATEMENT VARCHAR(3500) ASCII,
    COMPONENT_REVISIONTESTREPORTS  VARCHAR(3500) ASCII
) AS
xmlparse = exa.import_script('STAGING.VI_XMLPARSE')

def run(ctx):
	return xmlparse.parse_component(ctx, ctx.URL,ctx.USERNAME,ctx.PASSWORD)
/
