CREATE OR REPLACE python3 scalar SCRIPT STAGING.VI_DELIVERY (URL VARCHAR(3500) ASCII, USERNAME VARCHAR(3500), PASSWORD VARCHAR(3500))
EMITS (
    DELIVERY_GUID VARCHAR(3500) ASCII,
    DELIVERY_CBDNUMBER VARCHAR(3500) ASCII,
    DELIVERY_REVISIONALM  VARCHAR(3500) ASCII,
    DELIVERY_TITLE  VARCHAR(3500) ASCII,
    DELIVERY_CUSTOMER VARCHAR(3500) ASCII,
    DELIVERY_DELIVEREDDATE VARCHAR(3500) ASCII,
    DELIVERY_DELIVERYTYPE VARCHAR(3500) ASCII,
    DELIVERY_DELIVERYNUMBER VARCHAR(3500) ASCII,
    DELIVERY_ECUNAME VARCHAR(3500) ASCII,
    DELIVERY_INDBDATE VARCHAR(3500) ASCII,
    DELIVERY_PRODUCTTITLE VARCHAR(3500) ASCII,
    DELIVERY_PROGRAMTITLE VARCHAR(3500) ASCII,
    DELIVERY_RELTYPE VARCHAR(3500) ASCII,
    DELIVERY_BISBETA VARCHAR(3500) ASCII,
    DELIVERY_BISSAFETYRELEVANTC VARCHAR(3500) ASCII,
    DELIVERY_TESTEDDERIVATE VARCHAR(3500) ASCII,
    COMPONENT_NAME  VARCHAR(3500) ASCII,
    COMPONENT_VERSION  VARCHAR(3500) ASCII
) AS
xmlparse = exa.import_script('STAGING.VI_XMLPARSE')

def run(ctx):
	return xmlparse.parse_delivery(ctx, ctx.URL,ctx.USERNAME,ctx.PASSWORD)
/
