CREATE OR REPLACE python3 scalar SCRIPT STAGING.VI_METRIC (URL VARCHAR(3500) ASCII, USERNAME VARCHAR(3500), PASSWORD VARCHAR(3500))
EMITS (
	COMPONENT_NAME VARCHAR(3500) ASCII,
    COMPONENT_VERSION VARCHAR(3500) ASCII,
    SPECMETRIC_NAME  VARCHAR(3500) ASCII,
    METRIC_NAME  VARCHAR(3500) ASCII,
    METRIC_VALUE VARCHAR(3500) ASCII
) AS
xmlparse = exa.import_script('STAGING.VI_XMLPARSE')

def run(ctx):
	return xmlparse.parse_metric(ctx, ctx.URL,ctx.USERNAME,ctx.PASSWORD)
/