CREATE OR REPLACE python3 scalar SCRIPT STAGING.VI_RELEASE (URL VARCHAR(3500) ASCII, USERNAME VARCHAR(3500), PASSWORD VARCHAR(3500))
EMITS (
	PRODUCT_NAME VARCHAR(3500) ASCII,
    RELEASE_CREATIONDATEALM VARCHAR(3500) ASCII,
    RELEASE_CREATIONDATESVN VARCHAR(3500) ASCII,
    RELEASE_GUID VARCHAR(3500) ASCII,
    RELEASE_LASTMODDATE VARCHAR(3500) ASCII,
    RELEASE_MODTIMEALM VARCHAR(3500) ASCII,
    RELEASE_REVISIONALM VARCHAR(3500) ASCII,
    RELEASE_REVISIONSVN VARCHAR(3500) ASCII,
    RELEASE_VERSION VARCHAR(3500) ASCII,
    COMPONENT_GUID VARCHAR(3500) ASCII,
    COMPONENT_CMPPKGNAME VARCHAR(3500) ASCII,
    COMPONENT_VERSION VARCHAR(3500) ASCII
) AS
xmlparse = exa.import_script('STAGING.VI_XMLPARSE')

def run(ctx):
	return xmlparse.parse_release(ctx, ctx.URL,ctx.USERNAME,ctx.PASSWORD)
/