apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: "datavaultbuilder/api:rel_5_tg"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
        - name: CONNECTION_POOL
          value: "30"
        - name: TIMEZONE
          value: "Europe/Berlin"
        - name: DVB_TAG
          value: "rel_5_b2.4"
        volumeMounts:
        - name: dvb-secrets-vol
          mountPath: /etc/secrets
        - name: files
          mountPath: /files
      volumes:
      - name: dvb-secrets-vol
        secret:
          secretName: dvb-secrets
      - name: files
        persistentVolumeClaim:
          claimName: files
---
apiVersion: v1  
kind: PersistentVolumeClaim
metadata:
  name: files
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  clusterIP: None
  selector:
    app: api
  ports:
  - port: 80
    targetPort: 80
