apiVersion: apps/v1
kind: Deployment
metadata:
  name: connectionpool
spec:
  replicas: 1
  selector:
    matchLabels:
      app: connectionpool
  template:
    metadata:
      labels:
        app: connectionpool
    spec:
      containers:
      - name: connectionpool
        image: "datavaultbuilder/connection_pool:rel_5_tg"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
        - name: AUTHENTICATOR_PASSWORD_FILE
          value: "/etc/secrets/authenticator_password"
        - name: CORE_POOL_MAX_CONNECTIONS
          value: "20"
        - name: CLIENTDB_POOL_MAX_CONNECTIONS
          value: "20"
        - name: TIMEZONE
          value: "Europe/Berlin"
        - name: DVB_TAG
          value: "rel_5_b2.4"
        volumeMounts:
        - name: dvb-secrets-vol
          mountPath: /etc/secrets
        - name: files
          mountPath: /files
      volumes:
      - name: dvb-secrets-vol
        secret:
          secretName: dvb-secrets
      - name: files
        persistentVolumeClaim:
          claimName: files
---
apiVersion: v1  
kind: PersistentVolumeClaim
metadata:
  name: files
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: Service
metadata:
  name: connectionpool
spec:
  clusterIP: None
  selector:
    app: connectionpool
  ports:
  - port: 80
    targetPort: 80
