apiVersion: v1
kind: Secret
data:
  core_dbadmin_password: c3RhcnQxMjMK
  authenticator_password: c3RhcnQxMjMK
  scheduler_password: c3RhcnQxMjMK
  systems_password_private_key_password: c3RhcnQxMjMK
  systems_password_private_key: c3RhcnQxMjMK
  systems_password_public_key: c3RhcnQxMjMK
  datavault_builder_license: |-
    d2NGTUE3b3djS1M2K2Z6c0FSQUFnQVQ4TXNlbC8zajRHSkwzV25KeXpoVDF5R2R1ZnYxbUU3Zllt
    ZjRHNlV6bUI1Tk81SWlldlBsVA0Ka2tiaUxjaFNtTzNiVkRTdjQzT284K0dNUFZlNTQwU21ObXFL
    eEl4K1p5SWppQ3FPYmlWNzY2YWRFN3RqL1RtOWo3YkhKMlE0ZFplUw0KbTIzNDV5Y3NNVDlFMHVi
    N0IwZkpOdDBpWjJyUXd2bXJBYTUyZjNQQXROYyt4b1pHcnBaVFpJdW9ZQXpLRWJNZGFWTHFaSThu
    MHdVTA0KZ1dUTjErSGIySFQ2RjgwNjdsNEdWeXBOVUlJRm5OOGQ0OXpPTzd6Z3ozaTdPUUtsSmhL
    K24yTkNLeUNjNzc1TGtNTWhIZE1laWxzTQ0KV3BhQ0VNMG1iK3R5VjFqTWhGaFdSQ0RnVVN2L3d0
    dFhNTmRUUVJOVGhJTTdIYUpaQTAyOE5wR2dXR20wQ3RtWk4yTGc4L2pSMnFlNw0KNE9iMGRFcTZ3
    eUxqcVh0RWh6eTd5UVIrTlgxVXNqVFpYQnY2Rjd2eHdzcm9Mdkx1RHNldzIrOEh1UGZpZnhJRkJE
    R3ZGMXU2VCtLTw0KTDJwNWYwejlsV1czcmtnVGNxeTBhV1FuMFJlRVYxbGVmd1FRWmRTcFFrN2xR
    OThUcnBwTHcrNS9kMGxPZjFyT0V2MHNYK25YcjUwUQ0KT1RWVnk5Q1J3TFhPaWNHUFA4WFNBNjBs
    SEorcmdMTlFjREh0SklYTjZzVlVlYS9nVXNQNzJPZHFscEtxWGtvNy9Cek1Ec3R4d1hKTw0KTWlu
    M3VtS3NKSlFqc3FJVmZwU1BraUNzdTlPUXQvQWRKN1JGM0RwTUpQVTZxSmErRUNPY2NnNjZlOXdS
    cnZTT01qdDVLaVVpNXArRA0KblBPS1ZyU2w1cS9aM3hXWC9TUFN3QlFCbWVXOVU4WmxDUkxtQnNQ
    L2pJRFE0dGdINEczYXRPVVVZM2J0V2dSSlNWc2JPQTBITlJkag0KNzFNNHN1UGNDNE41cE1ZUnNY
    eVVDcTR1TUNDaTFpcHBpcWE5amJ4YUE0VXpIMEZIZ0tBeWZGemordjNEREZPaWFwMU5LM01SS3RO
    RQ0KN3VIeW1aRjFLSnVlUHFEK2tqTHpLdEFxRHdldy9SUTE3TzY0cytlYWxKaG4xRGczeGc3K0xX
    SGVVc0N1L3lDRlhwMS9kNVp2U1NONA0KckxqN1E3cHFIeWk5QUw5eVNUZWtkdVJUMU9pZXFlaCtP
    QVByNXRpaVNpZ09EdkxCR3dCNkI5T0dVZXRPbXlVT1MzOG1iTzE4TS9xTw0KeWc9PQ==
metadata:
  name: dvb-secrets
type: Opaque
---
