apiVersion: apps/v1
kind: Deployment
metadata:
  name: superset
spec:
  replicas: 1
  selector:
    matchLabels:
      app: superset
  template:
    metadata:
      labels:
        app: superset
    spec:
      containers:
      - name: superset
        image: "preset/superset:tg"
        command: ["flask"]
        args: ["run", "-p", "8088", "--with-threads", "--reload", "--debugger", "--host=0.0.0.0"]
        ports:
        - containerPort: 8088
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: superset
spec:
  ports:
  - port: 8088
    protocol: TCP
    targetPort: 8088
  selector:
    app: superset
  sessionAffinity: None
  type: ClusterIP
