apiVersion: apps/v1
kind: Deployment
metadata:
  name: webgui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webgui
  template:
    metadata:
      labels:
        app: webgui
    spec:
      containers:
      - name: webgui
        image: "datavaultbuilder/webgui:rel_5_tg"
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
        - name: DAV_USER
          value: dvb
        - name: DAV_PASSWORD
          value: start123
        - name: DISABLE_IPV6
          value: "false"
        - name: TIMEZONE
          value: "Europe/Berlin"
        - name: DVB_TAG
          value: "rel_5_b2.4"
        volumeMounts:
        - name: core-dbadmin-password
          mountPath: /etc/secrets
        - name: files
          mountPath: /files
      volumes:
      - name: core-dbadmin-password
        secret:
          secretName: dvb-secrets
      - name: files
        persistentVolumeClaim:
          claimName: files
---
apiVersion: v1  
kind: PersistentVolumeClaim
metadata:
  name: files
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: Service
metadata:
  name: webgui
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: webgui
  sessionAffinity: None
  type: ClusterIP
