version: 2

sources:
    - name: xml
      schema: staging
      tables:
        - name: vi_xml_component
        - name: vi_xml_delivery
        - name: vi_xml_metric
        - name: vi_xml_release
    - name: PSA
      schema: BUSINESS_RULES
      tables:
        - name: XMLMETRIC_S_XMLINTERFACE
    - name: RAW
      schema: BUSINESS_RULES
      tables:
        - name: COMPONENT_S_DBT_STAGE
